### ISSUE TITLE
Time Compression

### ISSUE THREAD

**Issue by CapnScurvy** [UnderminedArcus/sh4fix#13]
Time Compression disrupts the Campaign Mission files when “spawning” ships/convoys in-game.

**Comment by Propbeanie** [comment]
c. Time Compression also does not "anticipate" an encounter with enemy vessels (air, land, water) until actually "seen" by the sensors. By the time the game and computer react, the player may be beyond, or even in the middle of having their submarine destroyed. Is there any way to predict and encounter sooner than what the game does currently, and drop the TC level sooner? I know that the SSI / Aegis version of Silent Hunter from back when only went to 2048, but seemed more responsive and better at it than the "newer" version 4 here, which might have something to do with dealing with 3D animation... dunno.

**Comment by UnderminedArcus** [comment]
I'll split these up. Please do not be shy to create many issues. It's better to have many, narrow, precise issues to work on than just a few, which are convoluted and only superficially related. See #16 .

**Comment by UnderminedArcus** [comment]
Can you clarify this issue? Does the game crash when you TC in a campaign mission? Can save games not be reloaded?

**Comment by Propbeanie** [comment]
If you are referring to CapnScurvy's comment, labeled a "Bug", what a player sees is a "pause", or "hiccup" when the game is spawning something. Your boat normally proceeds across the screen at a set rate, and you'll notice that it will "stop" for a few milliseconds or so, then continue. We have no way of knowing for certain if it is a "spawn" that is happening, but oftentimes, just after seeing a "hiccup" in the game, the player will encounter an enemy vessel or group. That little hitch in the display lets you know to look out. Some folks consider it a "feature". Most of us do not.

**Comment by UnderminedArcus** [comment]
It's likely that they're related. I'll look into that.
